app_api:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api_users_login:
    path: /api/v1/users/login
